[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NETLIFY_USE_MISE = "false"
  NETLIFY_SKIP_MISE = "true"
  NODE_VERSION = "22"
  VITE_API_URL = "https://backend-zltm.onrender.com/api"


# Proxy API requests to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://backend-zltm.onrender.com/api/:splat"
  status = 200
  force = true

# SPA Fallback Redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


